// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptHostKeyChange(arg1:string,arg2:number):Promise<void>;

export function BackupToFTP():Promise<Record<string, any>>;

export function BackupToR2():Promise<Record<string, any>>;

export function BackupToSFTP():Promise<Record<string, any>>;

export function BackupToWebdav():Promise<Record<string, any>>;

export function CompressItem(arg1:string,arg2:string):Promise<void>;

export function ConnectSSH(arg1:string,arg2:string):Promise<void>;

export function DeleteConnection(arg1:string):Promise<boolean>;

export function DeleteItem(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DisconnectSSH(arg1:string):Promise<void>;

export function DoQuit():Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function GetCommandHistory(arg1:string):Promise<string>;

export function GetConnections():Promise<Array<main.Connection>>;

export function GetFTPConfig():Promise<Record<string, any>>;

export function GetGlobalCommandHistory():Promise<string>;

export function GetParamHistory():Promise<string>;

export function GetQuickCommands():Promise<string>;

export function GetR2Config():Promise<Record<string, any>>;

export function GetSFTPConfig():Promise<Record<string, any>>;

export function GetServerStaticInfo(arg1:string):Promise<Record<string, any>>;

export function GetSyncMode():Promise<string>;

export function GetTerminalCwd(arg1:string):Promise<string>;

export function GetWebdavConfig():Promise<Record<string, string>>;

export function GetWsPort():Promise<number>;

export function IsPortableVersion():Promise<boolean>;

export function ListDir(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function ListFTPBackups():Promise<Array<Record<string, any>>>;

export function ListR2Backups():Promise<Array<Record<string, any>>>;

export function ListSFTPBackups():Promise<Array<Record<string, any>>>;

export function ListWebdavBackups():Promise<Array<Record<string, any>>>;

export function Mkdir(arg1:string,arg2:string):Promise<void>;

export function OpenTerminal(arg1:string):Promise<string>;

export function PingServer(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ReadFile(arg1:string,arg2:string):Promise<string>;

export function ReadPrivateKeyFile():Promise<string>;

export function ReconnectWithPassword(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function RenameItem(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestoreFromFTPFile(arg1:string):Promise<Record<string, any>>;

export function RestoreFromR2File(arg1:string):Promise<Record<string, any>>;

export function RestoreFromSFTPFile(arg1:string):Promise<Record<string, any>>;

export function RestoreFromWebdavFile(arg1:string):Promise<Record<string, any>>;

export function SaveCommandHistory(arg1:string,arg2:string):Promise<void>;

export function SaveConnection(arg1:main.Connection):Promise<main.Connection>;

export function SaveFTPConfig(arg1:Record<string, string>):Promise<void>;

export function SaveGlobalCommandHistory(arg1:string):Promise<void>;

export function SaveParamHistory(arg1:string):Promise<void>;

export function SaveQuickCommands(arg1:string):Promise<void>;

export function SaveQuickCommandsLocal(arg1:string):Promise<void>;

export function SaveR2Config(arg1:Record<string, string>):Promise<void>;

export function SaveSFTPConfig(arg1:Record<string, string>):Promise<void>;

export function SaveWebdavConfig(arg1:Record<string, string>):Promise<void>;

export function SetSyncMode(arg1:string):Promise<void>;

export function SyncFromFTP():Promise<Record<string, any>>;

export function SyncFromR2():Promise<Record<string, any>>;

export function SyncFromSFTP():Promise<Record<string, any>>;

export function SyncFromWebdav():Promise<Record<string, any>>;

export function SystemInfo(arg1:string):Promise<Record<string, any>>;

export function TestFTPConnection(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function TestR2Connection(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function TestSFTPConnection(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function TestWebdavConnection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UncompressItem(arg1:string,arg2:string):Promise<void>;

export function UpdateApp(arg1:string,arg2:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<void>;

export function UploadFileContent(arg1:string,arg2:string,arg3:string,arg4:Array<number>):Promise<void>;

export function UploadLocalDir(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadLocalFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;

export function WriteWsOutput(arg1:string,arg2:Array<number>):Promise<void>;
