// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptHostKeyChange(arg1, arg2) {
  return window['go']['main']['App']['AcceptHostKeyChange'](arg1, arg2);
}

export function BackupToFTP() {
  return window['go']['main']['App']['BackupToFTP']();
}

export function BackupToR2() {
  return window['go']['main']['App']['BackupToR2']();
}

export function BackupToSFTP() {
  return window['go']['main']['App']['BackupToSFTP']();
}

export function BackupToWebdav() {
  return window['go']['main']['App']['BackupToWebdav']();
}

export function CompressItem(arg1, arg2) {
  return window['go']['main']['App']['CompressItem'](arg1, arg2);
}

export function ConnectSSH(arg1, arg2) {
  return window['go']['main']['App']['ConnectSSH'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteItem'](arg1, arg2, arg3);
}

export function DisconnectSSH(arg1) {
  return window['go']['main']['App']['DisconnectSSH'](arg1);
}

export function DoQuit() {
  return window['go']['main']['App']['DoQuit']();
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function GetCommandHistory(arg1) {
  return window['go']['main']['App']['GetCommandHistory'](arg1);
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetFTPConfig() {
  return window['go']['main']['App']['GetFTPConfig']();
}

export function GetGlobalCommandHistory() {
  return window['go']['main']['App']['GetGlobalCommandHistory']();
}

export function GetParamHistory() {
  return window['go']['main']['App']['GetParamHistory']();
}

export function GetQuickCommands() {
  return window['go']['main']['App']['GetQuickCommands']();
}

export function GetR2Config() {
  return window['go']['main']['App']['GetR2Config']();
}

export function GetSFTPConfig() {
  return window['go']['main']['App']['GetSFTPConfig']();
}

export function GetServerStaticInfo(arg1) {
  return window['go']['main']['App']['GetServerStaticInfo'](arg1);
}

export function GetSyncMode() {
  return window['go']['main']['App']['GetSyncMode']();
}

export function GetTerminalCwd(arg1) {
  return window['go']['main']['App']['GetTerminalCwd'](arg1);
}

export function GetWebdavConfig() {
  return window['go']['main']['App']['GetWebdavConfig']();
}

export function GetWsPort() {
  return window['go']['main']['App']['GetWsPort']();
}

export function IsPortableVersion() {
  return window['go']['main']['App']['IsPortableVersion']();
}

export function ListDir(arg1, arg2) {
  return window['go']['main']['App']['ListDir'](arg1, arg2);
}

export function ListFTPBackups() {
  return window['go']['main']['App']['ListFTPBackups']();
}

export function ListR2Backups() {
  return window['go']['main']['App']['ListR2Backups']();
}

export function ListSFTPBackups() {
  return window['go']['main']['App']['ListSFTPBackups']();
}

export function ListWebdavBackups() {
  return window['go']['main']['App']['ListWebdavBackups']();
}

export function Mkdir(arg1, arg2) {
  return window['go']['main']['App']['Mkdir'](arg1, arg2);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function PingServer(arg1, arg2) {
  return window['go']['main']['App']['PingServer'](arg1, arg2);
}

export function ReadFile(arg1, arg2) {
  return window['go']['main']['App']['ReadFile'](arg1, arg2);
}

export function ReadPrivateKeyFile() {
  return window['go']['main']['App']['ReadPrivateKeyFile']();
}

export function ReconnectWithPassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReconnectWithPassword'](arg1, arg2, arg3, arg4);
}

export function RenameItem(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameItem'](arg1, arg2, arg3);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function RestoreFromFTPFile(arg1) {
  return window['go']['main']['App']['RestoreFromFTPFile'](arg1);
}

export function RestoreFromR2File(arg1) {
  return window['go']['main']['App']['RestoreFromR2File'](arg1);
}

export function RestoreFromSFTPFile(arg1) {
  return window['go']['main']['App']['RestoreFromSFTPFile'](arg1);
}

export function RestoreFromWebdavFile(arg1) {
  return window['go']['main']['App']['RestoreFromWebdavFile'](arg1);
}

export function SaveCommandHistory(arg1, arg2) {
  return window['go']['main']['App']['SaveCommandHistory'](arg1, arg2);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveFTPConfig(arg1) {
  return window['go']['main']['App']['SaveFTPConfig'](arg1);
}

export function SaveGlobalCommandHistory(arg1) {
  return window['go']['main']['App']['SaveGlobalCommandHistory'](arg1);
}

export function SaveParamHistory(arg1) {
  return window['go']['main']['App']['SaveParamHistory'](arg1);
}

export function SaveQuickCommands(arg1) {
  return window['go']['main']['App']['SaveQuickCommands'](arg1);
}

export function SaveQuickCommandsLocal(arg1) {
  return window['go']['main']['App']['SaveQuickCommandsLocal'](arg1);
}

export function SaveR2Config(arg1) {
  return window['go']['main']['App']['SaveR2Config'](arg1);
}

export function SaveSFTPConfig(arg1) {
  return window['go']['main']['App']['SaveSFTPConfig'](arg1);
}

export function SaveWebdavConfig(arg1) {
  return window['go']['main']['App']['SaveWebdavConfig'](arg1);
}

export function SetSyncMode(arg1) {
  return window['go']['main']['App']['SetSyncMode'](arg1);
}

export function SyncFromFTP() {
  return window['go']['main']['App']['SyncFromFTP']();
}

export function SyncFromR2() {
  return window['go']['main']['App']['SyncFromR2']();
}

export function SyncFromSFTP() {
  return window['go']['main']['App']['SyncFromSFTP']();
}

export function SyncFromWebdav() {
  return window['go']['main']['App']['SyncFromWebdav']();
}

export function SystemInfo(arg1) {
  return window['go']['main']['App']['SystemInfo'](arg1);
}

export function TestFTPConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestFTPConnection'](arg1, arg2, arg3, arg4);
}

export function TestR2Connection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestR2Connection'](arg1, arg2, arg3, arg4);
}

export function TestSFTPConnection(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['TestSFTPConnection'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TestWebdavConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestWebdavConnection'](arg1, arg2, arg3);
}

export function UncompressItem(arg1, arg2) {
  return window['go']['main']['App']['UncompressItem'](arg1, arg2);
}

export function UpdateApp(arg1, arg2) {
  return window['go']['main']['App']['UpdateApp'](arg1, arg2);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function UploadFileContent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadFileContent'](arg1, arg2, arg3, arg4);
}

export function UploadLocalDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadLocalDir'](arg1, arg2, arg3);
}

export function UploadLocalFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadLocalFile'](arg1, arg2, arg3);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2, arg3);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}

export function WriteWsOutput(arg1, arg2) {
  return window['go']['main']['App']['WriteWsOutput'](arg1, arg2);
}
